#pragma config(Sensor, S1,     der,            sensorLightActive)
#pragma config(Sensor, S2,     izq,            sensorLightActive)
#pragma config(Motor,  motorA,          mder,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mizq,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

  int bco_bajo=64;
  int bco_alto=66;
  int ngo_bajo=35;
  int ngo_alto=40;
  int vde_bajo=57;
  int vde_alto=60;
  int ama_bajo=45;
  int ama_alto=48;

  int ade = 30;
  int len = -20;
  int alc = 40;
  int alt = 0;
  int ciclos = 0;
  int limite = 1800;


	while (true){
		  //SI ALGUN SENSOR DETECTA EL COLOR AMARILLO SE DETIENE
      if (((SensorValue[S1]>=ama_bajo) && (SensorValue[S1]<=ama_alto)) || ((SensorValue[S2]>= ama_bajo) && (SensorValue[S2]<=ama_alto)))  {
  	     ciclos=ciclos+1;
  	     if (ciclos>limite) {
            motor[mder]=alt;
  	        motor[mizq]=alt;
  	      }

      } else {
         // SI EL SENSOR IZQUIERDO DETECTA EL NEGRO ACELERA EL MOTOR DERECHO
         if ((SensorValue[S1]>=ngo_bajo) && (SensorValue[S1]<=ngo_alto)){
             motor[mder]=len;
             motor[mizq]=alc;
             ciclos = 0;
         } else {
             // SI EL SENSOR DERECHO DETECTA EL NEGRO ACELERA EL MOTOR IZQUIERDO
             if ((SensorValue[S2]>=ngo_bajo) && (SensorValue[S2]<=ngo_alto)){
                motor[mder]=alc;
                motor[mizq]=len;
                ciclos = 0;
             } else {
                motor[mder]=ade;
                motor[mizq]=ade;
                ciclos = 0;
             }
         }
      }
  }
}
