#pragma config(Sensor, S2,     ,               sensorLightActive)
#pragma config(Sensor, S3,     ,               sensorLightActive)
#pragma config(Sensor, S4,     ,               sensorAnalog)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int lol=0;
int media=50;
task main()
{
	while(true){
	if(SensorValue[S2]<media){//sensor derecho
	 motor[motorB]=100;//motor derecho
	 motor[motorC]=-10;//motor izquierdo

	}
	if(SensorValue[S3]<media){//sensor izquierdo
	 motor[motorB]=-10;//motor derecho
	 motor[motorC]=100;//motor izquierdo

	}
		if(SensorValue[S2]>media&&SensorValue[S3]>media){//sensor izquierdo
	 motor[motorB]=35;//motor derecho
	 motor[motorC]=35;//motor izquierdo

	}
	if(SensorValue[S2]<media&&SensorValue[S3]<media){//sensor izquierdo
		lol=lol+1;
		if(lol>1){
     motor[motorB]=0;//motor derecho
	   motor[motorC]=0;//motor izquierdo
		}
		else{
	 motor[motorB]=35;//motor derecho
	 motor[motorC]=35;//motor izquierdo
}

	}

	wait1Msec(1);
}


}
