#pragma config(Sensor, S1,     izq,            sensorLightActive)
#pragma config(Sensor, S2,     der,            sensorNone)
#pragma config(Motor,  motorA,          mder,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          mizq,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true){
      if (((SensorValue[S1]>= 55) && (SensorValue[S1]<=65)) || ((SensorValue[S2]>= 55) && (SensorValue[S2]<=65)))  {
  	     motor[mder]=0;
  	     motor[mizq]=0;
        } else {
        motor[mder]=50;
        motor[mizq]=50;
      }
  }


}
